[project]
name = "team-artemis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-community>=0.3.0",
    "langchain-google-genai>=4.2.0",
    "langgraph>=1.0.8",
]
